### ISSUE TITLE
说明

### ISSUE THREAD

**Issue by Mr-xn** [ce-automne/SunloginRCE#1]
那个项目不是我写的,我只是当做备份导 ^-^ 原作者是 @TRYblog 感谢你的二开，更好用，有时间 你也可以整合 https://github.com/Ryze-T/CNVD-2022-10270-LPE 读取 本地日志直接提取端口完成本地提权利用

**Comment by ce-automne** [comment]
哈哈谢谢，当时在工作中因为用到了这个漏洞，就临时二开了，本地提权的项目挺好的，我就不整合了00

**Comment by yulangx** [comment]
希望添加一个成功之后自动保存到文本的功能
